#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/db?CharacterEncoding=UTF-8
#  username: root
#  password: 16436130

#加载其他yml文件
spring:
  #加载其他配置文件
  profiles:
    active: abc,def
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?CharacterEncoding=UTF-8
    username: root
    password: 16436130
  #jedis缓存
  redis:
    host: 60.205.184.10
    port: 6379

#设置tomcat端口
server:
  port: 80

# 配置日志打印级别
logging:
  level:
    com.zps: debug
    org.springframework: info

#mybatis配置信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #扫描包，起别名
  type-aliases-package: com.zps.pojo

