server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:16436130@localhost:27017
      database: xc_cms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /