server:
  port: 10086
spring:
  application:
    name: eureka_server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
    # 不拉取服务
    fetch-registry: false